# Generated by Django 5.2.3 on 2025-06-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
